### ISSUE TITLE
Add genome fraction to the QC report

### ISSUE THREAD

**Issue by DOH-JDJ0303** [CDCgov/mycosnp-nf#105]
**Is your feature request related to a problem? Please describe.**
The current QC report does not include genome fraction, which is crucial for evaluating reference appropriateness and for identifying low quality and/or divergent samples that will reduce the size of the core genome.

**Describe the solution you'd like**
Genome fraction should be included in the QC report(s). This should be straightforward, as it is already determined by Qualimap at discrete coverage levels (see example: [genome_fraction_coverage.txt](https://github.com/CDCgov/mycosnp-nf/files/12165499/genome_fraction_coverage.txt)) and could be as simple as reporting genome fraction at 10X coverage, which is the default minimum depth required for a base to be included in the final output.

**Describe alternatives you've considered**
There are many ways to determine genome fraction (e.g., Quast). The method above seems like the most straightforward using existing pipeline outputs.

**Additional context**
I attached an example of the Qualimap output that would be used for this feature.

**Comment by urbagal** [comment]
Thank you for your suggestion.
