### ISSUE TITLE
question regarding --add_vcf_file

### ISSUE THREAD

**Issue by mstagliamonte** [CDCgov/mycosnp-nf#118]
Hi,

I would like to use the --add_vcf_file option to integrate results from a previous run, but I was wondering which vcf files should be included. Would you suggest to link the unfiltered individual sample files in the haplotype caller directory, or files from further downstream?

Best,
Max

**Comment by zmudge3** [comment]
Hi Max. Yes, the individual sample files found in `samples/<sample_id>/variant_calling/haplotypecaller` are the ones to use here. You may have already found this, but here is some additional information about this parameter: https://github.com/CDCgov/mycosnp-nf/wiki/USAGE#vcf-file-additions.

If you have any issues getting this to work, please let me know.

**Comment by mstagliamonte** [comment]
Great 👍

Thank you for your reply, I appreciate it.

Best,
Max
