### ISSUE TITLE
`mycosnp_create_sample_sheet.pl` does not include header line

### ISSUE THREAD

**Issue by rpetit3** [CDCgov/mycosnp-nf#24]
**Describe the bug**
When running the `mycosnp_create_sample_sheet.pl`  script it runs as expected but does not include the header line (`sample,fastq_1,fastq_2`)

**Impact**
When using the produced sample sheet, the first line is skipped. This makes the number of samples processed n-1.

**To Reproduce**
```
~/repos/mycosnp-nf/bin/mycosnp_create_sample_sheet.pl -i .
SRR7909249,./SRR7909249_1.fastq.gz,./SRR7909249_2.fastq.gz
SRR7909282,./SRR7909282_1.fastq.gz,./SRR7909282_2.fastq.gz

nextflow run ~/repos/mycosnp-nf/main.nf --input ../samples.csv --ref_dir ../docker/reference/GCA_016772135/
-profile docker --skip_phylogeny
....
[1a/4018ee] process > NFCORE_MYCOSNP:MYCOSNP:INPUT_CHECK:LANE_MERGE (SRR7909249)          [100%] 1 of 1 ✔
...
```

**Expected behavior**
```
~/repos/mycosnp-nf/bin/mycosnp_create_sample_sheet.pl -i .
sample,fastq_1,fastq_2
SRR7909249,./SRR7909249_1.fastq.gz,./SRR7909249_2.fastq.gz
SRR7909282,./SRR7909282_1.fastq.gz,./SRR7909282_2.fastq.gz

nextflow run ~/repos/mycosnp-nf/main.nf --input samples.csv --ref_dir ../docker/reference/GCA_016772135/ -profile docker --skip_phylogeny
...
[3f/fe3dc6] process > NFCORE_MYCOSNP:MYCOSNP:INPUT_CHECK:LANE_MERGE (SRR7909282)          [100%] 2 of 2 ✔
...
```

**Screenshots**

**Logs**
If applicable, please attach logs to help describe your problem.

**Desktop (please complete the following information):**
 - OS: Debian Buster

**Comment by mciprianoCDC** [comment]
Per Usage documentation, the correct script to use is mycosnp-nf/bin/mycosnp_full_samplesheet.sh <directory of fastq files> > new_samplesheet.csv

The script you are referencing is used internally within the shell script to create the full correct samplesheet.

**Comment by rpetit3** [comment]
awesome thank you!
