### ISSUE TITLE
Formatting and improving output docs, remove qc dir

### ISSUE THREAD

**Issue by LeuThrAsp** [CDCgov/mycosnp-nf#33]
Using other nf-core pipeline docs as guidance. Let me know if you have any suggestions!

**Comment by LeuThrAsp** [comment]
The qc directory in the results is redundant as it just houses the lines used to create the report in stats/qc_report

**Comment by mciprianoCDC** [comment]
@LeuThrAsp  Can you do a PR and update the modules.conf file to not publish files from that module?
