### ISSUE TITLE
file "combined_vcf-to-fasta.fasta" contains asterisks "*"

### ISSUE THREAD

**Issue by AspTryGlu** [CDCgov/mycosnp-nf#34]
**Describe the bug**
file "combined_vcf-to-fasta.fasta" contains asterisks "*"

**Impact**
The file can not be used in MEGA to generates phylogenetic trees

**Additional context**
-As far as I know the asterisks could be representing spanning deletions

-This issue was previously fixed in mycoSNP-genflow when version 0.19 was released.
(from a John's email message:) "mycosnp-gatk-variants now filters asterisks with the awk commands provided by Broad"

-Sharing an part of an email from Broad about:
"
For example, this command will remove all sites of the SNP spanning deletion 
awk '$5 !~/[GATC],\*/' test.vcf > test_clean_step1.vcf

There possibly could be another more rare class of sites that has the reverse listing (*, [GATC]), and these could be removed by a more general awk command:
awk '$5 !~/\*/' test_clean_step1.vcf > test_clean.vcf
""

**Comment by mciprianoCDC** [comment]
Closed by commit 61fc18a55e63350fe0ca600e8ee6dddcf12fa192
