### ISSUE TITLE
Read count differences for few samples

### ISSUE THREAD

**Issue by urbagal** [CDCgov/mycosnp-nf#67]
**Describe the bug**

The read count in the qc_report.txt does not match the real read count of the fastq input files. 
This varies from sample to sample and suggests an issue with the way the reads are counted.

**Impact**
discarding wrong samples for downstream analysis.

**To Reproduce**
Since the qc_report.txt is created after the downsampling step, the issue lies in the downsampling_rate-nf file. See the screenshot.

Change the command for counting reads from a fastq file in downsampling_rate-nf
:
zcat BXXXXX_1.fastq.gz|awk '/^@/ {lines+=1} END {print lines}'
1616686
to
echo $(zcat BXXXXX_1.fastq.gz|wc -l)/4|bc
1607577

**Expected behavior**
Correct read counts and other statistics in the qc_report should be helpful in removing bad samples only.

**Screenshots**
![Screenshot (80)](https://user-images.githubusercontent.com/80420597/168817421-10243910-2f1e-4d9b-98b0-9c9f4a01ffc1.png)

**Comment by sateeshperi** [comment]
#41

**Comment by cjjossart** [comment]
@LeuThrAsp and I are currently trying to reproduce the issue with the current version.

**Comment by mciprianoCDC** [comment]
Closes with merge.
