### ISSUE TITLE
Add snpEff sub-workflow for variant annotation

### ISSUE THREAD

**Issue by hseabolt** [CDCgov/mycosnp-nf#82]
**Is your feature request related to a problem? Please describe.**
Addition of new feature to create richer, more informative output repots from variant calling steps of MycoSNP

**Describe the solution you'd like**
Would like to annotate potential variants of interest in CDS regions.

**Comment by jwarnn** [comment]
Hello @hseabolt; I work at UPHL and we have been using mycosnp for a while and we would also like to implement snpEff into the mycosnp workflow. Just wondering if we could help make progress with this. nf-core has a module for snpEff which includes a docker container; there is also a docker container on STAPHB which could be used.  Anything we could help out with? Thanks!

**Comment by hseabolt** [comment]
snpEff functionality was included in a recent feature enhancement, closing this issue.
