### ISSUE TITLE
Default params.rate runs unneeded processes

### ISSUE THREAD

**Issue by jwarnn** [CDCgov/mycosnp-nf#83]
**Describe the bug**
The nextflow.config defines params.rate = 1; this parameter effects the behavior of the local module DOWNSAMPLE_RATE which also sends variables to SEQTK_SAMPLE to subsample the fastq files. When params.rate = 1 DOWNSAMPLE_RATE tells SEQTK_SAMPLE to randomly sample the exact number of reads available. 

**Impact**
At the very least this is wasted computation that should be avoided. This has also caused some cloud computing problems for my organization, UPHL, where the SEQTK_SAMPLE process is using lots of resources causing time and cost issues.

**To Reproduce**
This is the default behavior of the workflow; using the nextflow.config file. 

**Expected behavior**
I would think that the default config does not need to be change but how the sub-workflow runs could avoid this issue. Something like:
mycosnp-nf/subworkflows/local/bwa-pre-process.nf
line 43-50
```
SEQKIT_PAIR(reads)
if (params.rate == 1) {
FAQCS(SEQKIT_PAIR.out.reads)
}
else {
DOWNSAMPLE_RATE(SEQKIT_PAIR.out.reads, reference[0], params.coverage, params.rate)

ch_seq_samplerate = SEQKIT_PAIR.out.reads.join(DOWNSAMPLE_RATE.out.downsampled_rate.map{ meta, sr, snr -> [ meta, snr]})
    
SEQTK_SAMPLE(ch_seq_samplerate)
FAQCS(SEQTK_SAMPLE.out.reads)
}
BWA_MEM(FAQCS.out.reads, reference[2], true)
``` 
Lines 69 to 80 would also need to be modified because SEQTK_SAMPLE.out.versions would be undefined, maybe ``` SEQTK_SAMPLE.out.versions.ifEmpty('NA')```.

**Additional Details**
If my understanding is correct and you agree with the issue; I would be happy to submit a PR to address it. Thank you.

**Comment by elasekness** [comment]
This would be hugely helpful to me too.  I'm having the same issues.

**Comment by rpetit3** [comment]
To add onto this issue, I would consider completely dropping the `rate` parameter and just use `coverage` with a default of 0 (no downsampling)

In the current version `rate` is only used here: https://github.com/CDCgov/mycosnp-nf/blob/master/modules/local/downsample_rate.nf#L25 and in order to reduce to a coverage you have to change `rate` to something that is not 1. 

Going off @jwarnn recommendation, something like:
```
SEQKIT_PAIR(reads)
if (params.coverage == 0) {
    FAQCS(SEQKIT_PAIR.out.reads)
}
else {
    DOWNSAMPLE_RATE(SEQKIT_PAIR.out.reads, reference[0], params.coverage)
    ch_seq_samplerate = SEQKIT_PAIR.out.reads.join(
        DOWNSAMPLE_RATE.out.downsampled_rate.map{ meta, sr, snr -> [ meta, snr]}
    )
    SEQTK_SAMPLE(ch_seq_samplerate)
    FAQCS(SEQTK_SAMPLE.out.reads)
}
BWA_MEM(FAQCS.out.reads, reference[2], true)
```

Based on the above you could then drop the if block in the `DOWNSAMPLE_RATE` module

**Comment by urbagal** [comment]
Kindly submit a PR to include it in v1.5

**Comment by jwarnn** [comment]
Yes I can work on getting a PR sent over. I am pretty sure; I already have the code written somewhere. I would like to test it before creating the PR.
