### ISSUE TITLE
running this in Google Cloud?

### ISSUE THREAD

**Issue by mjpworth** [CDCgov/mycosnp-nf#85]
sorry for the possibly snarky question, but has this workflow been tested in Google Cloud?

is anyone running it in Google Cloud. We continue to have substantial and repeated problems in getting it to run to completion in Google Cloud.

**Comment by elasekness** [comment]
Yup same here.  Every time I get one process to work another issue arises - from tmpdir specifications, to memory issues, to GCP not liking certain notations. I've even had issues with where directories are placed.  I haven't been able to get this thing to run successfully except for the test data set.  I've been troubleshooting this thing for weeks.  I've gotten to the point where I just comment out things that don't work. It's running on a sample of 20 and halfway complete, fingers crossed all the modifications have worked.
