### ISSUE TITLE
NFCORE_MYCOSNP:MYCOSNP:BWA_PREPROCESS:QUALIMAP_BAMQC

### ISSUE THREAD

**Issue by PalanikumarPalanichamy** [CDCgov/mycosnp-nf#95]
**Describe the bug**
Process `NFCORE_MYCOSNP:MYCOSNP:BWA_PREPROCESS:QUALIMAP_BAMQC (SAMPLE)` terminated with an error exit status (137)

command to run nextflow:
./nextflow run mycosnp-nf/main.nf -profile docker --input auris-testing/new_samplesheet.csv --fasta auris-testing/B8441.fasta

**Impact**
Trying to understand, build and compare similar pipeline with nextflow. Now, the comparison is delayed.

**Expected behavior**
Expecting to run successful the pipeline. The test run show no error. But, clear details about usage required.

**Desktop**
 - OS: Ubuntu 20.04
 - Nextflow: 23.04.0
 - System: 16GB RAM, 8 core CPU

**Additional context**
I did faced same issue for some other samples. I have tried a total of 4 times running single sample, out of that 1 time the run is complete with no error. I have also faced this error: unknown recognition error type: groovyjarjarantlr4.v4.runtime.LexerNoViableAltException

Though pipeline is running, errors are constant.

**Comment by urbagal** [comment]
We have a newer version with a few bugs fixed. If you get the same error, try using singularity instead of docker
